services:
  db:
    image: postgres:16
    container_name: secure_notes_db
    environment:
      POSTGRES_USER: pppppp
      POSTGRES_PASSWORD: pppppp
      POSTGRES_DB: ppppppp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d secure_notes"]
      interval: 5s
      timeout: 5s
      retries: 15

  backend:
    build: .
    container_name: secure_notes_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy


volumes:
  pgdata:

